# Comment out the probes you don't need
# CAREFUL: yaml is super sensitive to spaces - don't use tabs

# Simulation parameters
sim_params:
    sim_name: 'AbacusSummit_base_c000_ph001'                                 # which simulation
    sim_dir: '/global/cfs/projectdirs/desi/cosmosim/Abacus/halo_light_cones/'  # where is the simulation
    output_dir: '/pscratch/sd/e/epaillas/ds_boss/HOD/lightcone'     # where to output galaxy mocks
    # subsample_dir: '/pscratch/sd/s/sihany/summit_subsample_lc/' # where to output subsample data
    subsample_dir: '/pscratch/sd/e/epaillas/summit_subsamples/lightcones/' # where to output subsample data
    # subsample_dir: '/pscratch/sd/b/boryanah/AbacusHOD_scratch/mocks_lc_subsample/'
    cleaned_halos: '/global/cfs/projectdirs/desi/cosmosim/Abacus/cleaning/' # not used
    Nthread_load: 3
    z_mock: 0.575                                                      
    halo_lc: True

prepare_sim:
    Nparallel_load: 3 # best for cori haswell node  

# HOD parameters
HOD_params:
    use_particles: True
    want_ranks: True               # want to implement satellite profile flexiblities?
    want_AB: True               # want to implement assembly bias?              
    density_sigma: 3               # scale radius in Mpc / h for local density calculation
    tracer_flags:                  # which tracer do we want?
        LRG: True 
        ELG: False
        QSO: False
    want_rsd: True                 # want RSD? 
    write_to_disk: False

    LRG_params:
        logM_cut: 12.87
        logM1: 14.06
        sigma: 0.02083802
        alpha: 1.15
        kappa: 0.42
        alpha_c: 0.22
        alpha_s: 0.94
        s: 0
        s_v: 0
        s_p: 0
        s_r: 0
        Acent: 0
        Asat: 0
        Bcent: 0
        Bsat: 0
        ic: 1.0

fit_params:
    logM_cut: [0, 'LRG']
    logM1: [1, 'LRG']
    sigma: [2, 'LRG']
    alpha: [3,  'LRG']
    kappa: [4, 'LRG']
    # alpha_c: [5, 'LRG']
    # alpha_s: [6, 'LRG']
    # Bcent: [7, 'LRG']
    # Bsat: [8, 'LRG']

# ===========================================================================================
# The following dictionaries are for using the provided emcee/likelihood templates. They 
# are not needed for using the AbacusHOD class and running HODs. 

# parameters that indicate where the observed data that you would like to fit live. 
data_params:
    tracer_density_mean:
        LRG: 0.0001 # 3.0 # (mpc/h)^-3
    tracer_density_std:
        LRG: 3.0e-5 # (mpc/h)^-3


# Configuration parameters for emcee
ch_config_params:
    path2output: /global/homes/e/epaillas/pscratch/ds_boss/HOD/lightcone/
    chainsPrefix: phasetrain_velbias_AB
    nthread: 256

